---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 11.16.4

platforms:
  - name: redhat
    driver:
      vagrantfile_erb: Vagrantfile.erb
      box: redhat-5-chef
      box_url: http://bit.ly/1qBrpXj
      network:
        - ['private_network', {ip: '172.28.128.30'}]
      customize:
        memory: 2048
        cpus: 2

provisioner:
  name: chef_solo

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[yum-epel::default]
      - recipe[oracle::default]
    attributes:
      yum:
        epel:
          enabled: false
      oracle:
